name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags-ignore:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Code Linting
        uses: sibiraj-s/action-eslint@v4.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extensions: 'js'
          annotations: true


  openapi:
    name: OpenAPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate OpenAPI file
        run: npm run openapi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          path: openapi/openapi.json
          if-no-files-found: warn
