name: Publish

on:
  push:
    tags:
      - v*

env:
  NODE: 14

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: npm install

      - name: NPM publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: GitHub release
        uses: ncipollo/release-action@v1.8.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
