name: Publish

on:
  push:
    branches:
      - main

env:
  NODE: 12

jobs:
  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/releases/')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE }}

      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
