name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs:
      - publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/v}"

      - name: Get Changelog entry
        uses: mindsers/changelog-reader-action@v2.2.2
        id: changelog
        with:
          version: ${{ steps.version.outputs.version }}
          path: ./CHANGELOG.md

      - name: Release to GitHub
        uses: ncipollo/release-action@v1.13.0
        with:
          name: Release v${{ steps.changelog.outputs.version }}
          body: ${{ steps.changelog.outputs.changes }}
          prerelease: ${{ steps.changelog.outputs.status == 'prereleased' }}
          draft: ${{ steps.changelog.outputs.status == 'unreleased' }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
